-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 30, 2020 at 05:22 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `chronhibdev_test2020sortv2`
--

-- --------------------------------------------------------

--
-- Table structure for table `search`
--

CREATE TABLE `search` (
  `ID` int(11) NOT NULL,
  `Creator` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Query` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`Query`)),
  `Timestamp` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `search`
--

INSERT INTO `search` (`ID`, `Creator`, `Query`, `Timestamp`) VALUES
(1, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(2, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(3, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(4, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(5, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(6, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(7, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(8, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(9, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(10, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(11, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(12, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(13, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(14, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]},{\"table\":\"LEMMATA\",\"column\":[\"ID\",\"Lemma\",\"Meaning\",\"DIL_Headword\",\"Part_Of_Speech\",\"Class\",\"Gender\",\"Etymology\",\"Comments\",\"Lang\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(15, NULL, '{\"tableColumns\":[{\"table\":\"LEMMATA\",\"column\":[\"ID\",\"Lemma\",\"Meaning\",\"DIL_Headword\",\"Part_Of_Speech\",\"Class\",\"Gender\",\"Etymology\",\"Comments\",\"Lang\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(16, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(17, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]},{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(18, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]},{\"table\":\"LEMMATA\",\"column\":[\"ID\",\"Lemma\",\"Meaning\",\"DIL_Headword\",\"Part_Of_Speech\",\"Class\",\"Gender\",\"Etymology\",\"Comments\",\"Lang\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(19, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(20, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]},{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(21, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(22, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(23, NULL, '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(24, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(25, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\",\"Title\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Part_Of_Speech\",\"negated\":\"NOT\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"noun\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(26, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Part_Of_Speech\",\"negated\":\"NOT\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"noun\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(27, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Part_Of_Speech\",\"negated\":\"NOT\",\"operator\":\"\",\"comparator\":\"LIKE\",\"comparatorVal\":\"noun\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(28, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]},{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Part_Of_Speech\",\"negated\":\"NOT\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"noun\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(29, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Part_Of_Speech\",\"negated\":\"NOT\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"noun\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(30, NULL, '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Part_Of_Speech\",\"negated\":\"NOT\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"noun\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(31, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"NOT\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"},{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"NOT\",\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(32, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"NOT\",\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(33, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]},{\"table\":\"SENTENCES\",\"column\":[\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"NOT\",\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(34, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Textual_Unit\",\"negated\":\"\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"lugdag\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(35, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Textual_Unit\",\"negated\":\"\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Lugdag\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(37, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Thes\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Textual_Unit\",\"negated\":\"\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Lugdag\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(38, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Contributor\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Textual_Unit\",\"negated\":\"\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Lugdag\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(40, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Textual_Unit\",\"negated\":\"\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Lugdag\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(41, NULL, '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(42, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(43, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(44, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(45, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(46, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(47, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Gen.\"},{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"NOT\",\"caseSensitive\":true,\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.du.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(48, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Gen.\"},{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"NOT\",\"caseSensitive\":false,\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.du.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(49, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Gen.\"},{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"NOT\",\"caseSensitive\":true,\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.du.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(50, NULL, '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Text_ID\",\"Sort_ID\"]},{\"table\":\"SENTENCES\",\"column\":[\"Textual_Unit\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Gen.\"},{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"NOT\",\"caseSensitive\":true,\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.du.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(51, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Text_ID\",\"Sort_ID\"]},{\"table\":\"SENTENCES\",\"column\":[\"Textual_Unit\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Gen.\"},{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"NOT\",\"caseSensitive\":true,\"operator\":\"AND\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.du.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(52, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(53, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\",\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(54, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(55, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(56, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"0\"},{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"OR\",\"comparator\":\"contains\",\"comparatorVal\":\"1\"},{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"OR\",\"comparator\":\"contains\",\"comparatorVal\":\"2\"},{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"NOT\",\"caseSensitive\":true,\"operator\":\"OR\",\"comparator\":\"contains\",\"comparatorVal\":\"4\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(57, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"0\"},{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"OR\",\"comparator\":\"contains\",\"comparatorVal\":\"1\"},{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"OR\",\"comparator\":\"contains\",\"comparatorVal\":\"2\"},{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"NOT\",\"caseSensitive\":true,\"operator\":\"OR\",\"comparator\":\"contains\",\"comparatorVal\":\"4\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(58, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Textual_Unit\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"lugdag\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(59, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Textual_Unit\",\"negated\":\"\",\"caseSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"lugdag\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(60, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(61, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]},{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(62, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(63, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Secondary_Meaning\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"caseSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"gen.\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(64, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":false,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '0000-00-00 00:00:00'),
(65, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 02:44:55'),
(66, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 02:45:42'),
(67, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:08:54'),
(68, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"Colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:09:02'),
(69, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:12:35'),
(70, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:13:03'),
(71, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":false,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:13:23'),
(72, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:13:35'),
(73, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"0\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:32:34'),
(74, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"ID\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"0\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 04:35:05'),
(75, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 05:53:23'),
(76, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":false,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 05:53:33'),
(77, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 05:53:49'),
(78, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 05:54:20'),
(79, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"Translation\"]}],\"conditions\":[{\"table\":\"SENTENCES\",\"column\":\"Translation\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"colman\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-14 06:08:36'),
(80, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"within\",\"comparatorVal\":\"1,2,3,4\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-15 06:50:45'),
(81, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '2020-11-15 08:41:21'),
(82, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 08:26:21'),
(83, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 08:33:07'),
(84, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"LEMMATA\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"Title\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"of\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 08:45:47'),
(85, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"SENTENCES\",\"column\":[\"Textual_Unit\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 08:47:49'),
(86, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"SENTENCES\",\"column\":[\"Textual_Unit\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"caseSensitive\":true,\"accentSensitive\":true,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 08:49:48'),
(87, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"LEMMATA\",\"column\":[\"ID\",\"Lemma\",\"Meaning\",\"DIL_Headword\",\"Part_Of_Speech\",\"Class\",\"Gender\",\"Etymology\",\"Comments\",\"Lang\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"=\",\"comparatorVal\":\"terfochraicc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:35:59'),
(88, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"Comments\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Comments\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"possibly i-stem\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:40:06');
INSERT INTO `search` (`ID`, `Creator`, `Query`, `Timestamp`) VALUES
(89, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:47:33'),
(90, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"LEMMATA\",\"column\":[\"Lemma\",\"ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:48:08'),
(91, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"LEMMATA\",\"column\":[\"Lemma\"]},{\"table\":\"SENTENCES\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:48:22'),
(92, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"LEMMATA\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:50:13'),
(93, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:50:36'),
(94, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:51:04'),
(95, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:51:30'),
(96, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:54:10'),
(97, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 11:55:09'),
(98, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 14:17:56'),
(99, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"Morph\",\"Lemma\",\"Text_Unit_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"augm\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 15:19:47'),
(100, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Morph\",\"Lemma\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"within\",\"comparatorVal\":\"augm\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 15:22:33'),
(101, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Morph\",\"Lemma\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Analysis\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"augm\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 15:23:02'),
(102, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Morph\",\"Lemma\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"within\",\"comparatorVal\":\"798 ,6760 ,7392 ,7398 ,8764 ,9851 ,10793 ,13281 ,13534 ,13653 ,14110\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 15:25:23'),
(103, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 15:32:43'),
(104, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"Title\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"Lemma\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"orc\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-18 15:32:58'),
(105, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"LEMMATA\",\"column\":[\"ID\",\"Lemma\",\"Meaning\",\"DIL_Headword\",\"Part_Of_Speech\",\"Class\",\"Gender\",\"Etymology\",\"Comments\",\"Lang\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"LEMMATA\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"=\",\"comparatorVal\":\"cach\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-23 12:55:06'),
(106, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"=\",\"comparatorVal\":\"98668\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-23 13:36:28'),
(107, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"LEMMATA\",\"column\":[\"ID\",\"Lemma\",\"Meaning\",\"DIL_Headword\",\"Part_Of_Speech\",\"Class\",\"Gender\",\"Etymology\",\"Comments\",\"Lang\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Lemma\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"=\",\"comparatorVal\":\"cach\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-23 14:01:25'),
(108, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '2020-11-24 00:17:55'),
(109, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"within\",\"comparatorVal\":\"1,2,3,4\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-24 01:11:25'),
(110, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '2020-11-24 02:07:40'),
(111, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-25 02:18:04'),
(112, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-25 02:28:21'),
(113, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0,\"page\":2}}', '2020-11-25 02:28:36'),
(114, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-25 02:28:45'),
(115, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-25 02:55:12'),
(116, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-25 14:19:11'),
(117, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":36,\"page\":2}}', '2020-11-25 15:08:41'),
(118, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":36,\"page\":2}}', '2020-11-25 15:09:39'),
(119, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":36,\"page\":2}}', '2020-11-25 15:27:25'),
(120, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-25 15:28:56'),
(121, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-25 15:35:04'),
(122, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-26 16:04:10'),
(123, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"MORPHOLOGY\",\"column\":\"Morph\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"=\",\"comparatorVal\":\"cach\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-26 20:07:49'),
(124, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-29 05:25:35'),
(125, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"TEXT\",\"column\":[\"ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":0}}', '2020-11-30 13:19:10'),
(126, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":2}}', '2020-11-30 14:42:30'),
(127, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0,\"page\":2}}', '2020-11-30 14:56:10'),
(128, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":300,\"page\":2}}', '2020-11-30 14:56:36'),
(129, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":300,\"page\":0}}', '2020-11-30 15:09:07'),
(130, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"TEXT\",\"column\":[\"ID\",\"Text_ID\",\"Title\",\"Date\",\"Dating_Criteria\",\"Edition\",\"MSS\",\"Digital_MSS\",\"Thes\",\"Contributor\",\"Created_Date\",\"MS_Checked\",\"Reason_Of_MS_Choice_And_Editorial_Policy\",\"Sort_ID\"]},{\"table\":\"LEMMATA\",\"column\":[\"ID\",\"Lemma\",\"Meaning\",\"DIL_Headword\",\"Part_Of_Speech\",\"Class\",\"Gender\",\"Etymology\",\"Comments\",\"Lang\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":true,\"duplicateRows\":true,\"limit\":0}}', '2020-11-30 15:39:42'),
(131, 'godstime.osarobo@mu.ie', '{\"tableColumns\":[{\"table\":\"SENTENCES\",\"column\":[\"ID\",\"Text_ID\",\"Text_Unit_ID\",\"Locus1\",\"Locus2\",\"Locus3\",\"Textual_Unit\",\"Translation\",\"Textual_Notes\",\"Translation_Notes\",\"Latin_Text\",\"Translation_From_Latin\",\"Variant_Readings\",\"Subunit\",\"Sort_ID\"]},{\"table\":\"MORPHOLOGY\",\"column\":[\"ID\",\"Text_Unit_ID\",\"Stressed_Unit\",\"Morph\",\"Expected_Morph\",\"Lemma\",\"Secondary_Meaning\",\"Analysis\",\"Comments\",\"Augm\",\"Rel\",\"Trans\",\"Depend\",\"Depon\",\"Contr\",\"Hiat\",\"Mut\",\"Causing_Mut\",\"Hybrid_form\",\"Problematic_Form\",\"Onomastic_Complex\",\"Onomastic_Usage\",\"SpecialCharacter\",\"Syntactic_ID\",\"Phrase_structure_tree\",\"Syntactic_Unit\",\"Phrase_type\",\"Phrase\",\"Syntactic_Unit_Translation\",\"id_of_change\",\"Var_Status_1\",\"Var_Status_2\",\"Var_Status_3\",\"Var_Status_4\",\"Var_Status_5\",\"Text_ID\",\"Sort_ID\"]}],\"conditions\":[{\"table\":\"TEXT\",\"column\":\"ID\",\"negated\":\"\",\"accentSensitive\":false,\"operator\":\"\",\"comparator\":\"contains\",\"comparatorVal\":\"\"}],\"options\":{\"noConditions\":false,\"duplicateRows\":true,\"limit\":0}}', '2020-11-30 15:47:28');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `search`
--
ALTER TABLE `search`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `Creator` (`Creator`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `search`
--
ALTER TABLE `search`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=132;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
